package enums;

public enum ETileAbility {

	IGNORE_PLACEMENT_RULES_WHEN_PLACING_LAND_TILES, PROTECTION_FROM_DECLINE, PROTECTION_FROM_PLAGUE,
	PROTECTION_FROM_EARTHQUAKE, PROTECTION_FROM_DROUGHT, PROTECTION_FROM_TEMPEST, SUPPLY_ROUND

}
