package enums;

public enum ETileAbility {

	IGNORE_PLACEMENT_RULES_WHEN_PLACING_LAND_TILES,
	PROTECTION_FROM_DECLINE,
	PROTECTION_FROM_PLAGUE,
	PROTECTION_FROM_EARTHQUAKE,
	PROTECTION_FROM_DROUGHT,
	PROTECTION_FROM_TEMPEST,
	SUPPLY_ROUND,
	IF_TWENTY_LUXURY_GOODS_THEN_HIGHER_NUMBER_OF_THE_TWO_SCORES,
	ONE_POINT_FOR_EVERY_TWO_COINS,
	FOUR_POINTS_FOR_EACH_POPULATION,
	SACRIFICE_INHABITANTS

}
